### ISSUE TITLE
How to define kick reason?

### ISSUE THREAD

**Issue by zvukoper** [BytexDigital/BytexDigital.BattlEye.Rcon#13]
It seems any kick results in an "Admin Kick". Can a reason be specified?

**Comment by RyanTT** [comment]
Hello, it seems we missed this in our command implementation. Could you try adding this class and then using the constructor overload to test if the reason appears like this? If it works, I'll push a new nuget version with this fixed.

```csharp
    public class KickWithReasonCommand : Command
    {
        /// <summary>
        /// Requests the server to remove the given player ID from the server.
        /// </summary>
        /// <param name="playerId"></param>
        public KickCommand(int playerId) : base($"kick {playerId}")
        {
        }

        public KickCommand(int playerId, string reason) : base($"kick {playerId} {reason}")
        {
        }
    }
```

**Comment by zvukoper** [comment]
> Hello, it seems we missed this in our command implementation. Could you try adding this class and then using the constructor overload to test if the reason appears like this? If it works, I'll push a new nuget version with this fixed.

Thanks for the reply, RyanTT. I'm a bit a newbie coder. I grabbed the DLL and added it to my solution. I think you're asking to add it to your code and compile? I'm not sure I will do it properly.

**Comment by RyanTT** [comment]
Please try this [pre release version](https://www.nuget.org/packages/BytexDigital.BattlEye.Rcon/1.0.3-beta.4). It should allow you to define a kick reason with a constructor overload

**Comment by zvukoper** [comment]
Thank you. I will try soon.

**Comment by zvukoper** [comment]
Works perfectly. Thank you!
