### ISSUE TITLE
A onlinePlayers BUG?

### ISSUE THREAD

**Issue by elstp** [BytexDigital/BytexDigital.BattlEye.Rcon#17]
![image](https://user-images.githubusercontent.com/25148156/182185909-3110a391-c97f-447c-8dc2-0881e5c75800.png)

How can a server with 10 people and no one return 0

**Comment by elstp** [comment]
Returns 0 regardless of whether the server is occupied

**Comment by RyanTT** [comment]
Hi, sadly I am unable to reproduce this issue.

What .NET version are you using?
Would you be able to setup a test server and test the same on there?

**Comment by elstp** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by elstp** [comment]
> Hi, sadly I am unable to reproduce this issue.
> 
> What .NET version are you using? Would you be able to setup a test server and test the same on there?

I have tested, your test project is NET5.0, I use your test project is no problem. If I were to build a single NET framework 4.7.2, executing allPlayers would return 0 directly

**Comment by RyanTT** [comment]
I have changed the TestClient .csproj to .NET 4.7.2

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BytexDigital.BattlEye.Rcon\BytexDigital.BattlEye.Rcon.csproj" />
  </ItemGroup>

</Project>
```

The player count is still returned correctly. Can you please try to do the same with the TestClient?

**Comment by elstp** [comment]
> 

I am also surprised that there is a project that returns correctly, but a new console program is created, and it returns 0. The code is exactly the same. I don't know where the problem is.

**Comment by elstp** [comment]
I would also like to ask if there is a reconnection mechanism, because RCON is easy to break.

**Comment by RyanTT** [comment]
> I would also like to ask if there is a reconnection mechanism, because RCON is easy to break.

Yes, the client will automatically reconnect if the connection is lost.


> I am also surprised that there is a project that returns correctly, but a new console program is created, and it returns 0. The code is exactly the same. I don't know where the problem is.

I'll check with a new project soon. Apart from this, is there any reason you are using .NET Framework 4.7 instead of .NET 5.0?

**Comment by elstp** [comment]
> > I would also like to ask if there is a reconnection mechanism, because RCON is easy to break.
> 
> Yes, the client will automatically reconnect if the connection is lost.
> 
> > I am also surprised that there is a project that returns correctly, but a new console program is created, and it returns 0. The code is exactly the same. I don't know where the problem is.
> 
> I'll check with a new project soon. Apart from this, is there any reason you are using .NET Framework 4.7 instead of .NET 5.0?

I don't know what the difference is between.NET5.0 and NET framework 4.7.2, but I have been habitually using 4.7.2 to make software.. I'm not a professional

**Comment by RyanTT** [comment]
.NET Framework is not recommended anymore, as it is Windows-only and slower in performance.
.NET 5.0 or higher (for example .NET 6.0) are the recommended options for new software, I advise you to use that instead if it doesn't break anything in your projects. WinForms and WPF are also available for .NET 5.0.

**Comment by elstp** [comment]
So that's it!

**Comment by elstp** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
