### ISSUE TITLE
GetMissionsRequest doese not realized

### ISSUE THREAD

**Issue by EgoBrainProgrammer** [BytexDigital/BytexDigital.BattlEye.Rcon#2]
GetMissionsRequest doese not realized

```
RconClient networkClient = new RconClient("192.168.1.1", 2344, "pswd");

            bool requestSuccess = networkClient.Fetch(
                command: new GetMissionsRequest(),
                timeout: 5000,
                result: out string missions);
```

> InvalidOperationException

**Comment by RyanTT** [comment]
Hi, this command doesn't have it's return value interpretation done yet, I will add it once I setup an Arma server again for testing.

**Comment by EgoBrainProgrammer** [comment]
Hello.
It does not matter.
This task can be solved by .Send() method.

`
CommandNetworkRequest req = BEClient.Send("missions");
req.WaitUntilResponseReceived();
CommandNetworkResponse resp = (CommandNetworkResponse)req.Response;
string msg = resp.Content;
`

**Comment by RyanTT** [comment]
Are you able to provide me with the output that's written into `string msg`? Then I can implement it.

**Comment by EgoBrainProgrammer** [comment]
For my case:

> Missions on server:
> AntistasiTanoa�WarlordsOfThePacific.Tanoa.pbo
> [54]warfare_v54.altis.pbo
> [54]warfare_v54.chernarus.pbo
> [54]warfare_v54.Chernarus_winter.pbo
> [54]warfare_v54.Malden.pbo
> [54]warfare_v54.sara.pbo
> [54]warfare_v54.tanoa.pbo

**Comment by RyanTT** [comment]
Are you able to provide me with the mission names in the directory and how they are configured in your server.cfg? I'm unsure whether `[54]` actually marks some kind of versioning

**Comment by EgoBrainProgrammer** [comment]
This is a literal file names and nothing else...

**Comment by RyanTT** [comment]
I've added an implementation in df938d0 in the development branch if you want to check it out
