### ISSUE TITLE
SocketException

### ISSUE THREAD

**Issue by skyracer2012** [BytexDigital/BytexDigital.BattlEye.Rcon#4]
Yeah it seems like there is an issue in the BytexDigital.BattlEye.Rcon.NetworkConnection class.

Here is the full error:

> Anwendung: EvoRCON.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Net.Sockets.SocketException
   bei System.Net.Sockets.Socket.DoBeginReceiveFrom(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.EndPoint, System.Net.SocketAddress, System.Net.Sockets.OverlappedAsyncResult)
   bei System.Net.Sockets.Socket.BeginReceiveFrom(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.EndPoint ByRef, System.AsyncCallback, System.Object)
   bei System.Net.Sockets.UdpClient.BeginReceive(System.AsyncCallback, System.Object)
   bei System.Threading.Tasks.TaskFactory`1[[System.Net.Sockets.UdpReceiveResult, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncImpl(System.Func`3<System.AsyncCallback,System.Object,System.IAsyncResult>, System.Func`2<System.IAsyncResult,System.Net.Sockets.UdpReceiveResult>, System.Action`1<System.IAsyncResult>, System.Object, System.Threading.Tasks.TaskCreationOptions)
   bei System.Net.Sockets.UdpClient.ReceiveAsync()
   bei BytexDigital.BattlEye.Rcon.NetworkConnection+<Receive>d__21.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by RyanTT** [comment]
Hi,

under what circumstances does this error appear?
What .NET Framework version are you using?

**Comment by skyracer2012** [comment]
I think this occurs on restart of the arma server. I am using .NET Framework 4.7.1

**Comment by RyanTT** [comment]
Please try this beta build
https://www.nuget.org/packages/BytexDigital.BattlEye.Rcon/1.0.2-beta.3

**Comment by skyracer2012** [comment]
I did some intense testing its fixed now
