### ISSUE TITLE
GetPlayersRequest always return an empty list

### ISSUE THREAD

**Issue by Braendstrup** [BytexDigital/BytexDigital.BattlEye.Rcon#5]

**Comment by RednecksRevenge** [comment]
can confirm

**Comment by RyanTT** [comment]
Hi,

I am unable to recreate this issue, are you running the command like this?

```csharp
            bool requestSuccess = networkClient.Fetch(
                command: new GetPlayersRequest(),
                timeout: 5000,
                result: out List<Player> onlinePlayers);```

**Comment by NeutraleNull** [comment]
yes and i can also confirm the problem

**Comment by NeutraleNull** [comment]
I tracked the problem down to the regex expression in https://github.com/BytexDigital/BytexDigital.BattlEye.Rcon/blob/e78efb7a6ae03074181634037c9252e181ec3561/BytexDigital.BattlEye.Rcon/Commands/GetPlayersRequest.cs#L26
Trying to figure out what exactly is leading to no matches found.

**Comment by RednecksRevenge** [comment]
`(\d+) *(\d*\.\d*\.\d*\.\d*):(\d*) *(\d+) *(\S{32})\((\S+)\) (?:(.+) (\(Lobby\))|(.+))`
In the regex you are currently using you are only checking the first digits of the ip from 1 to unlimited and the other ones from 0-9.
With this one you check all digits from 0-unlimited.

**Comment by RyanTT** [comment]
Applied a fix based on #6 which I merged from dev into master as version https://www.nuget.org/packages/BytexDigital.BattlEye.Rcon/1.0.3-beta.1 with #7 . Please provide feedback whether this fixed your issue entirely.

**Comment by NeutraleNull** [comment]
The is in lobby detection is not working as intended. It always returns true.

**Comment by RyanTT** [comment]
Addressed the issue, please try version https://www.nuget.org/packages/BytexDigital.BattlEye.Rcon/1.0.3-beta.2

**Comment by NeutraleNull** [comment]
Works for me so far.

**Comment by Braendstrup** [comment]
I can confirm, it seems to work now
